#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/polargraphcontroller.jar:$APPDIR/lib/core.jar:$APPDIR/lib/diewald_CV_kit.jar:$APPDIR/lib/batikfont.jar:$APPDIR/lib/geomerative.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/controlP5.jar" polargraphcontroller
